### ISSUE TITLE
[FR]: Support Ubuntu 24.04

### ISSUE THREAD

**Issue by GregJohnStewart** [Epic-Breakfast-Productions/OpenQuarterMaster#599]
### Software

Core API, Base Station, Plugins- *, SNH - Station Captain, SNH - Infra - *

### Describe what you'd like to see

Things are, at time of writing, no bueno for OQM on Ubuntu 24.04.

It appears that there is an issue with the docker library for python:

```
May 09 20:01:21 oqm-b4-test bash[37613]: TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
May 09 20:01:21 oqm-b4-test bash[37613]: During handling of the above exception, another exception occurred:
May 09 20:01:21 oqm-b4-test bash[37613]: Traceback (most recent call last):
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/bin/oqm-captain", line 62, in <module>
May 09 20:01:21 oqm-b4-test bash[37613]:     ContainerUtils.ensureSharedDockerResources()
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/lib/oqm/station-captain/ContainerUtils.py", line 55, in ensureSharedDockerResources
May 09 20:01:21 oqm-b4-test bash[37613]:     client = docker.from_env()
May 09 20:01:21 oqm-b4-test bash[37613]:              ^^^^^^^^^^^^^^^^^
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/lib/python3/dist-packages/docker/client.py", line 96, in from_env
May 09 20:01:21 oqm-b4-test bash[37613]:     return cls(
May 09 20:01:21 oqm-b4-test bash[37613]:            ^^^^
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/lib/python3/dist-packages/docker/client.py", line 45, in __init__
May 09 20:01:21 oqm-b4-test bash[37613]:     self.api = APIClient(*args, **kwargs)
May 09 20:01:21 oqm-b4-test bash[37613]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
May 09 20:01:21 oqm-b4-test bash[37613]:     self._version = self._retrieve_server_version()
May 09 20:01:21 oqm-b4-test bash[37613]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 09 20:01:21 oqm-b4-test bash[37613]:   File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
May 09 20:01:21 oqm-b4-test bash[37613]:     raise DockerException(
May 09 20:01:21 oqm-b4-test bash[37613]: docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```
Made a bug against ubuntu to see what they say: https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348

### Describe alternatives you've considered

None

### Additional context

None

**Comment by GregJohnStewart** [comment]
Ubuntu bug finally fixed, works now
